blog/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

app_name = 'blog'

urlpatterns = [

    #using predefined class from django
    path('', TemplateView.as_view(template_name = 'blog/default.html'), name='home'),
    #path('show', views.showAll, name='show'),
    path('show', views.post_list, name='showall'),
    path('<slug:slug>/', views.post_detail, name='detail'),
    path('add', views.AddPost, name='addpost'),
    path('editpost/<str:slug>/', views.editPost, name='editpost'),
    path('deletepost/<str:slug>/', views.deletePost, name='deletepost'),
    path("tags/<int:tag_id>", views.list_posts_by_tag, name="tag")
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cloudtrail/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webassistant/', include('webassistant.urls')),
    path('register/', include('users.urls')),
    path('', include('blog.urls'))
]

webassistant/urls.py
# here we are import path from in-built django-urls
from django.urls import path
# here we are importing all the Views from the views.py file
from . import views


app_name = 'webassistant'

# a list of all the urls
urlpatterns = [
    path('home', views.home, name='home'),
    path('error-handler/', views.error_handler, name='error_handler'),
]

blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


# post tags
class Tag(models.Model):
    title = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.title

# post
class Post(models.Model):
    headline=models.CharField(max_length=255)
    slug=models.CharField(max_length=130, unique=True)
    #slug = models.SlugField(null=False, unique=True, max_length = 250)
    content=models.TextField()
    created_on=models.DateTimeField('date created', auto_now_add=True)
    updated_on=models.DateTimeField(auto_now=True)
    view_count=models.IntegerField(default=0)
    is_active=models.BooleanField(default=True)
    #image = models.ImageField(upload_to="images", blank=True, null=True)
    #image = models.FileField(upload_to='images/', null=True)
    image = models.ImageField(upload_to="images", blank=True, null=True)
    tags = models.ManyToManyField(to=Tag, related_name="posts", blank=True)
   
    class Meta:
        ordering = ['-created_on']
    
    def __str__(self):
        return self.headline



# post comment
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(default='anonymous', max_length = 100)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved_comment = models.BooleanField(default=True)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text
    

blog/forms.py
from django import forms
from .models import *
#from django.core.exceptions import ValidationError
#from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content','author']
        widget = {
            'author': forms.TextInput(attrs={'class':'form-control'}),
            'content': forms.Textarea(attrs={'class':'form-control'}),
        }

    #def clean_name(self):
    #    """Make sure people don't use my name"""
    #    data = self.cleaned_data['name']
    #    if not self.request.user.is_authenticated and data.lower().strip() == 'samuel':
    #        raise ValidationError("Sorry, you cannot use this name.")
    #    return data
    

class CustomMMCF(forms.ModelMultipleChoiceField):

    def label_from_instance(self, member):
        return '%s' % member.name

class BlogForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = '__all__'
        exclude = ('updated_on','created_on', 'is_active','view_count')

        headline = forms.CharField()
    
        tags = CustomMMCF(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple
        )
        #tags = forms.ModelMultipleChoiceField(
        #queryset=Tag.objects.all(),
        #widget=forms.CheckboxSelectMultiple
        #)



#class CommentForm(forms.ModelForm):
#
#    class Meta:
#        model = Comment
#        fields = {'content','author', 'authorEmail'}

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse

from datetime import datetime, timedelta
from .models import *
from .forms import BlogForm, CommentForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from django.urls import reverse_lazy
#from django.views import generic

#from django.views.generic import FormView
#from django.views.generic.detail import SingleObjectMixin
#from django.urls import reverse
#from .forms import CommentForm

from cloudtrail import app_settings


def app_info():
    app = {
    "title": app_settings.APP_NAME,
    "version": app_settings.APP_VER,
    "copyright": app_settings.APP_COPYRIGHT
    }
    return app

def list_posts_by_tag(request, tag_id):

    default_page = 1
    posts_per_page = app_settings.DEFAULT_PER_PAGE

    tag = get_object_or_404(Tag, id=tag_id)

    all_posts = Post.objects.filter(is_active=True, tags=tag)

    #let us read the page num from the GET, if not default to 1
    page_num = request.GET.get('page', default_page)

    paginator = Paginator(all_posts, per_page=posts_per_page)

    #print(paginator.num_pages)

    try:
        posts = paginator.page(page_num)
    except PageNotAnInteger:
        # if page is not an integer, deliver the first page
        posts = paginator.page(default_page)
    except EmptyPage:
        # if the page is out of range, deliver the last page
        posts = paginator.page(paginator.num_pages)

    context = {
        "tag_name": tag.title,
        "posts": posts,
        "app": app_info(),
    }

    return render(request, 'blog/post_list.html', context)


def post_list(request):
    #posts = Post.objects.filter(is_active=True).order_by('-created_on')

    default_page = 1
    posts_per_page = app_settings.DEFAULT_PER_PAGE


    all_posts = Post.objects.filter(is_active=True).order_by('-created_on')

    #let us read the page num from the GET, if not default to 1
    page_num = request.GET.get('page', default_page)

    paginator = Paginator(all_posts, per_page=posts_per_page)

    try:
        posts = paginator.page(page_num)
    except PageNotAnInteger:
        # if page is not an integer, deliver the first page
        posts = paginator.page(default_page)
    except EmptyPage:
        # if the page is out of range, deliver the last page
        posts = paginator.page(paginator.num_pages)

    

    context = {
        "tag_name": "all",
        "posts": posts,
        "app": app_info,
    }

    #paginate_by = 1
    return render(request, 'blog/post_list.html', context)

def post_detail(request, slug):
    template_name = 'blog/post_detail.html'
    post = get_object_or_404(Post, slug=slug)

    #update view count
    post.view_count = post.view_count+1
    post.updated_on = datetime.now()
    post.save()

    comments = post.comments.filter(approved_comment=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
            #success_url = reverse_lazy("thanks")
            #return redirect(success_url)

    else:
        comment_form = CommentForm()

    # similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.objects.filter(is_active=True).filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-created_on')[:6]


    return render(request, template_name, {'post': post,
                                           'similar_posts': similar_posts,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form})



def thanks(request):
    return HttpResponse("Thank you! Will get in touch soon.")

def AddPost(request):
    form = BlogForm()
    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('blog:showall')

    context = {'form': form}
    return render(request,'blog/addpost.html', context)


def deletePost(request, slug):
    post = get_object_or_404(Post, slug=slug)
    #if not request.user == recipe.author:
    #    return redirect('detail', recipe.id)
    #else:
    post.is_active = not post.is_active
    post.save()
    #post.updated_on = datetime
    return redirect('blog:showall')
    
def editPost(request, slug):
    post = get_object_or_404(Post, slug=slug)
    context = {
        'post': post
    }
    if request.method == 'GET':
        form = BlogForm(instance=post)
        context['form'] = form
        return render(request, 'blog/editpost.html', context)
    elif request.method == 'POST':
        form = BlogForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('blog:showall')
        else:
            form = BlogForm(instance=post)
            context['form'] = form
            return render(request, 'blog/editpost.html', context)
    return render(request, 'blog/editpost.html', context)

blog/templates/blog/addpost.html
{% extends 'base.html' %}

{% block content %}
  <h1>Add a new blog post</h1>
  
  <form enctype="multipart/form-data" action="" method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="SUBMIT">
</form>
  
{% endblock %}

blog/templates/blog/default.html
{% extends 'base.html' %}


{% block breadcrumb %} <h6>Welcome. Home Page</h6> {% endblock %}

{% block content %}

<div class="p-5 my-4 bg-light rounded-3">
  <h1>Table of Contents</h1>
  <ul class="list-unstyled">
    <li><a href={% url 'blog:showall' %}>All posts</a></li>
    <li><a href={% url 'webassistant:home' %}>Go to ChatGPT</a></li>
    <li>About Us</li>
    <li>Contact</li>
  </ul>
</div>

{% endblock %}

blog/templates/blog/editpost.html
{% extends "base.html" %}

{% block title %}

default page 

{% endblock %}


{% block content %}
<h3> You reached the edit page!</h3>


<div class="row text-center">

    <form enctype="multipart/form-data" method="POST"> 
        {% csrf_token %}
        <div class="container mt-4">
        {{ form.as_p }}
        <button class="btn btn-primary">Update Post</button>
        </div>
    </form>
   
</div>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}



<div class="container">
  <div class="row"><a href="{% url 'blog:showall' %}" class="btn btn-primary">Back to all posts</a></div>
  <div class="row">

    <div>
      {% for tag in post.tags.all %}
      <a href="{% url 'blog:tag' tag.id %}">
        {{tag}}
      </a>&nbsp;&nbsp;
      {% endfor %}
    </div>


    <div class="card" style="max-width: 100%;">
      <div class="row g-0">
        <div class="col-sm-5">
          <img src="{{ post.image.url }}" class="card-img-top h-100" alt="...">
        </div>
        <div class="col-sm-7">
          <div class="card-body">
            <h5 class="card-title">{{post.headline}}</h5>
            <p class="card-text">{{ post.content|safe }}</p>
            <a href="#" class="btn btn-primary stretched-link">published {{post.created_on }}</a>
            <p> {% for tag in post.tags.all %}
              <a href="{% url 'blog:tag' tag.id %}">
                {{tag}}
              </a> &nbsp;&nbsp;
              {% endfor %}
            </p>
          </div>
        </div>
      </div>
    </div>


  </div>
  <div>

    <div class="card-group">
      {% for post in similar_posts %}
      <div class="card">
        <img src="{{ post.image.url }}" class="img-thumbnail" alt="{{post.headline}}">
        <div class="card-body">
          <h5 class="card-title">{{post.headline}}</h5>
          <p class="card-text">{{post.content|truncatechars:65}}</p>
          <a href="{% url 'blog:detail' post.slug %}" class="btn btn-primary">Read more</a>
          <a href="{% url 'blog:editpost' post.slug %}" class="btn btn-primary">Edit</a>
          <a href="{% url 'blog:deletepost' post.slug %}" class="btn btn-primary">Delete</a>
        </div>
        <div class="card-footer">
          <small class="text-muted">Posted on {{ post.created_on }} by {{ post.author }}</small>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  <div class="row">

    <div class="form-group">
      <h5>Add comment</h5>
      <form method="POST" class="post-form">{% csrf_token %}
        {{ comment_form.as_p }} <br />
        <button type="submit" class="btn btn-primary">Add comment</button>

    </div>
    <hr />

    {% for comment in comments %}

    <div class="card text-center">
      
      <div class="card-body">
          
          <p class="card-text">{{comment.content | safe}}</p>
          <a href="#" class="btn btn-primary">by {{comment.author}}</a>
      </div>
      <div class="card-footer text-muted">{{comment.created_on |timesince}} ago</div>
  </div>

  
    {% endfor %}


  </div>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Blog</h1>
<a href="{% url 'blog:addpost' %}" class="btn btn-primary">Add a new post</a>

{% if tag_name %}
<h1>Showing posts with Tag: {{tag_name}}</h1>
{% else %}
<h1>Showing all Posts</h1>
{% endif %}

<div class="card-group">
  {% for post in posts %}
  <div class="card">
    <img src="{{ post.image.url }}" class="img-thumbnail" alt="{{post.headline}}">
    <div class="card-body">
      <h5 class="card-title">{{post.headline}}</h5>
      <p class="card-text">{{post.content|truncatechars:65}}</p>
      <a href="{% url 'blog:detail' post.slug %}" class="btn btn-primary">Read more</a>
      <a href="{% url 'blog:editpost' post.slug %}" class="btn btn-primary">Edit</a>
      <a href="{% url 'blog:deletepost' post.slug %}" class="btn btn-primary">Delete</a>
    </div>
    <div class="card-footer">
      <small class="text-muted">Posted on {{ post.created_on }} by {{ post.author }}</small>
    </div>
  </div>
  {% endfor %}
</div>
<br>
<hr>
<div>
  {% if posts.has_other_pages %}
  <ul class="pagination">
    {% if posts.has_previous %}
    <a href="?page={{ posts.previous_page_number }}">Previous Page</a>
    {% else %}
    Previous Page
    {% endif %} &nbsp;&nbsp;
    <span>
      Page {{ posts.number }} of {{ posts.paginator.num_pages }} &nbsp;&nbsp;
    </span>
    {% if posts.has_next %}
    <a href="?page={{ posts.next_page_number }}">Next Page</a>
    {% else %}
    Next Page
    {% endif %}
  </ul>
  {% endif %}
  
</div>
{% endblock %}

{% block footer %}

{{ app.version }}


{% endblock %}