blog/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

app_name = 'blog'

urlpatterns = [

    #using predefined class from django
    path('', TemplateView.as_view(template_name = 'blog/default.html'), name='home'),
    #path('show', views.showAll, name='show'),
    path('show', views.post_list, name='showall'),
    path('<slug:slug>/', views.post_detail, name='detail'),
    path('add', views.AddPost, name='addpost'),
    path('editpost/<str:slug>/', views.editPost, name='editpost'),
    path('deletepost/<str:slug>/', views.deletePost, name='deletepost'),
    path("tags/<int:tag_id>", views.list_posts_by_tag, name="tag")
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cloudtrail/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webassistant/', include('webassistant.urls')),
    path('register/', include('users.urls')),
    path('', include('blog.urls'))
]

users/urls.py
from django.urls import path
 
from users import views

app_name = 'appusers'

urlpatterns = [
    path('', views.register_user, name="register")
]

webassistant/urls.py
# here we are import path from in-built django-urls
from django.urls import path
# here we are importing all the Views from the views.py file
from . import views


app_name = 'webassistant'

# a list of all the urls
urlpatterns = [
    path('home', views.home, name='home'),
    path('error-handler/', views.error_handler, name='error_handler'),
]

templates/base.html
<!DOCTYPE html>
<html>

<head>
  <title>{% block title %}Cloudtrail{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  {% block extra_css %}{% endblock %}
</head>

<body>
  <div class="container bg-light">

    {% block navbar %}

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'blog:home' %}">Cloudtrail</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'webassistant:home' %}">ChatGPT</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:showall' %}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'appusers:register' %}">Register</a>
          </li>
        </ul>
      </div>
    </nav>

    {% endblock %}

    <div class="container-fluid">

      {% block breadcrumb %} {% endblock %}

    </div>



    <div class="container-fluid">

      {% block content %} {% endblock %}

    </div>



    <div class="container-fluid">

      {% block footer %}
      <div class="col-md-6">
        <p>Copyright © 2023 Lumos LLC</p>
        <p></p>
      </div>
      <div class="col-md-6 text-md-end">
        <a href="#" class="text-dark">Terms of Use</a>
        <span class="text-muted mx-2">|</span>
        <a href="#" class="text-dark">Privacy Policy</a>
      </div>
      {% endblock %}
      
    </div>

  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
  {% block extra_js %}{% endblock %}
</body>

</html>